[package]
name = "caligula"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.69"
bytesize = "1.2.0"
clap = { version = "4.1.8", features = ["derive", "cargo"] }
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = "0.3.26"
futures-io = "0.3.26"
inquire = "0.5.3"
interprocess = { version = "1.2.1", features = ["tokio", "tokio_support"] }
is-terminal = "0.4.4"
nix = { version = "0.26.2", default-features = false, features = ["fs"] }
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tokio-util = { version = "0.7.7", features = ["compat"] }
tracing = { version = "0.1.37", features = ["async-await", "log", "release_max_level_off", "valuable"] }
tracing-subscriber = "0.3.16"
tracing-unwrap = "0.10.0"
tui = "0.19.0"
valuable = { version = "0.1.0", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
test-case = "3.0.0"

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
strip = true

[target.aarch64-apple-darwin.dependencies]
libc = "0.2.139"

[build-dependencies]
bindgen = "0.64.0"
