[package]
name = "caligula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
async-bincode = "0.7.0"
bincode = "1.3.3"
bytesize = "1.2.0"
clap = { version = "4.1.8", features = ["derive", "cargo"] }
crossterm = "0.26.1"
futures = "0.3.26"
futures-core = "0.3.26"
inquire = "0.5.3"
is-terminal = "0.4.4"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
tracing = { version = "0.1.37", features = ["valuable", "async-await", "log"] }
tracing-subscriber = "0.3.16"
tui = "0.19.0"
udev = "0.7.0"
valuable = { version = "0.1.0", features = ["derive"] }
