[package]
name = "caligula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bytesize = "1.2.0"
clap = { version = "4.1.8", features = ["derive", "cargo"] }
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = "0.3.26"
futures-io = "0.3.26"
inquire = "0.5.3"
interprocess = { version = "1.2.1", features = ["tokio", "tokio_support"] }
is-terminal = "0.4.4"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tee_readwrite = "0.1.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tokio-util = { version = "0.7.7", features = ["compat"] }
toml = "0.7.2"
tracing = { version = "0.1.37", features = ["valuable", "async-await", "log"] }
tracing-subscriber = "0.3.16"
tui = "0.19.0"
udev = "0.7.0"
valuable = { version = "0.1.0", features = ["derive"] }
