on:
  workflow_call:
    inputs:
      build_runner:
        required: true
        type: string
      target_triple:
        required: true
        type: string
      do_e2e_tests:
        required: true
        type: boolean
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

env:
  nix_target: ".#packages.${{ inputs.target_triple }}.caligula"
  artifact: "caligula-${{ inputs.target_triple }}"

jobs:
  build:
    name: "Build using Nix"
    runs-on: ${{ inputs.build_runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = ${{ inputs.target_triple }}

      - uses: cachix/cachix-action@v12
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build ${{ env.nix_target }} --show-trace

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact }}
          path: result/bin/caligula

      - name: e2e test
        if: inputs.do_e2e_tests
        run: nix run ${{ env.nix_target }} -- --help

  e2e-test-fresh:
    name: e2e test on fresh ${{ inputs.smoke_test_runner }}
    runs-on: ${{ inputs.e2e_test_runner }}
    needs: build
    if: inputs.do_e2e_tests

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.artifact }}
        
    - name: Set permissions on artifact
      run: chmod +x caligula
      
    - name: Ensure the command runs
      run: ./caligula --help
