name: "CI"

on:
  push:

jobs:
  ci:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: ${{ matrix.params.build_runner }}
      target_triple: ${{ matrix.params.target_triple }}
      do_smoke_tests: ${{ matrix.params.do_smoke_tests }}
    secrets: inherit
    strategy:
      matrix:
        params:
          - build_runner: ubuntu-latest
            target_triple: x86_64-linux
            do_smoke_tests: true

          - build_runner: macos-latest
            target_triple: x86_64-darwin
            do_smoke_tests: true

          - build_runner: ubuntu-latest
            target_triple: aarch64-linux
            do_smoke_tests: false

          - build_runner: macos-latest
            target_triple: aarch64-darwin
            do_smoke_tests: false