name: "CI"

on:
  push:
  pull_request:

jobs:
  ci-x86_64-linux:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: ubuntu-latest
      e2e_test_runner: ubuntu-latest
      target_triple: x86_64-linux
      do_e2e_tests: true
    secrets: inherit

  ci-x86_64-darwin:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: macos-latest
      e2e_test_runner: macos-latest
      target_triple: x86_64-darwin
      do_e2e_tests: true
    secrets: inherit

  ci-aarch64-linux:
    uses: ./.github/workflows/ci-unix.yml
    with:
      build_runner: ubuntu-latest
      target_triple: aarch64-linux
      do_e2e_tests: false
    secrets: inherit
